
title   : Alex Rohleder - Investindo na Comunidade :)
email   : contato@alexrohleder.com.br
url     : https://blog.alexrohleder.com.br
baseurl : /blog/_site

github_username : alexrohleder96
disqus_shotname : alexrohlederblog

markdown  : kramdown
paginate  : 4
permalink : /:title.html
gems      : [
	"jekyll-paginate"
]
